# [START cloudbuild]
steps:
# This step runs the unit tests on the app
- name: 'gcr.io/cloud-builders/docker'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/vital-analogy-389705/my-repository/angular:ms1'
  - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/vital-analogy-389705/my-repository/angular:ms1'  
# [END cloudbuild]

# [START cloudbuild-trigger-cd]
# This step clones the angular-deployment-trigger repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud source repos clone angular-deployment-trigger && \
    cd angular-deployment-trigger && \
    git checkout candidate && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > hello-cloudbuild-env/kubernetes.yaml

# This step pushes the manifest back to angular-deployment-trigger
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd angular-deployment-trigger && \
    git add Deployment.yaml service.yml && \
    git commit -m "Deploying image us-central1-docker.pkg.dev/vital-analogy-389705/my-repository/angular:ms1
    Built from commit angular:ms1 of repository angular-deployment-trigger
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin candidate

# [END cloudbuild-trigger-cd]
