steps:
  # Step 1: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'Deployment.yml'
      - '-f'
      - 'service.yml'
    timeout: '600s'

options:
  logging: 'CLOUD_LOGGING_ONLY'
