  steps:
  # Step 1: Build Angular Application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
   
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
   
  # Step 2: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'your-deployment-file.yml'
      - '-f'
      - 'your-service-file.yml'
options:
  logging: CLOUD_LOGGING_ONLY   
