apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 3
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angularapp
          image: us-central1-docker.pkg.dev/vital-analogy-389705/my-repository/angular:ms1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
